### PR TITLE
24 menu filter search

### PR DESCRIPTION
**Pull request by Kaifeng20**

### CODE REVIEW

**Comment by RuntaoZhuge** [comment]
Did you forget to add you package.json?

**Comment by Kaifeng20** [comment]
> Did you forget to add you package.json?

**Comment by RuntaoZhuge** [comment]
I added the design to the figma can you have a look and change the styles. I believe that the filter should be able to handle multiselection as a dish can fit in more than one category. It would be good to have multiselection work

**Comment by RuntaoZhuge** [comment]
Can we have the out border removed?
image
Right now there are some issues:
1. The search box seems like pushing the whole thing to the right when selected
2. The dropdown text should be bold
3. The tags are having wrong border radius and font-color, paddings, and the cross should have a bit padding from the text and it should be black

**Pull request closed without merging**
